title: Jasper's Blog
author: J Davis
navbar-links:
  About Me: "A novice coder that enjoys product development"
  Resources:
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "TBD"



navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
