title: Jasper's Blog
author: J Davis
navbar-links:
  About Me: "A novice coder that enjoys product development"
  Resources:
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "TBD"

